docs(ja): periodic update
aws/copilot-cli pull request #2919
Opened 2021-10-14 00:45 UTC by isleys

docs(ja): periodic update

This PR updates the Japanese localized docs based on the changes in the English docs after the v1.11.0 tag(4e7d638) to the mainline(9298aed).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

2021-10-14 04:48 UTC, toricls requested changes
Thanks for the contribution @isleys! Left some feedback!

2021-10-14 04:48 UTC, toricls commented on site/content/docs/developing/publish-subscribe.ja.md
> +トピックの機能を表す名前が必要です。
Can we change this to "SNS トピックの機能を表す名前を付けましょう。" or something like that?

The essential points in my mind are:
- Let readers understand the word "トピック" is just one of SNS' concepts, and this may be the first time for readers to see "トピック"
- Although users must supply some kind of name here, whether naming the topic to "describe its function" is all up to users and not mandatory.

Let me hear your thoughts :)

2021-10-14 04:48 UTC, toricls commented on site/content/docs/developing/publish-subscribe.ja.md
> +Manifest の [`subscribe`](../manifest/worker-service/#subscribe) フィールドを使用して、Environment 内の他のサービスが公開する既存の SNS トピックへのサブスクリプションを定義します。この例では、前セクションの `api` サービスが公開する `orders` トピックを使用しています。また Worker Service
Can we use `ordersTopic` instead of `order` here? It's just a typo in the original English doc as well and I just created a PR to fix that [here](https://github.com/aws/copilot-cli/pull/2920).

2021-10-14 04:48 UTC, toricls commented on site/content/docs/developing/publish-subscribe.ja.md
> +Manifest の [`subscribe`](../manifest/worker-service/#subscribe) フィールドを使用して、Environment 内の他のサービスが公開する既存の SNS トピックへのサブスクリプションを定義します。この例では、前セクションの `api` サービスが公開する `orders` トピックを使用しています。また Worker Service
Also see the line 60 or 62 in this file, there is another `order` which should be fixed as well

2021-10-14 04:48 UTC, toricls commented on site/content/docs/include/common-svc-fields.ja.md
> +logging セクションには、ログ設定を含みます。このセクションでは、コンテナの [FireLens](https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/using_firelens.html) ログドライバ用のログ設定パラメータを設定できます。(設定例は[こちら](../developing/sidecars.
I'd prefer "ログドライバ用のパラメータを設定できます" for simplicity, comparing to the current sentence. Any thoughts?

2021-10-14 04:48 UTC, toricls commented on site/content/docs/include/command.jp.md
> +# あるいは文字列配列による指定も可能。
This is really my personal opinion, or I'm just thinking out loud, but maybe we should encourage users to use `Array of String` over `String` for both `CMD` and `ENTRYPOINT`, because IIRC Docker just ignores `CMD` if the `ENTRYPOINT` is a string value 🤔 This makes users hard to do troubleshooting, right?

Cc @efekarakus Can I get your opinion here? (I'm pinging you in a JP translation PR, but I believe this should not be a matter only for JP docs)

2021-10-14 04:48 UTC, toricls commented on site/content/docs/include/exec.ja.md
> +コンテナ内部でのインタラクティブなコマンド実行機能を有効化します。デフォルト値は `false` です。`$ copilot svc exec` コマンドの利用には、この値に `true` を指定しておく必要があります。
I love this translation (or localization?) here! I believe this is much easier to understand for users, excellent job @isleys!

2021-10-14 04:48 UTC, toricls commented on site/content/docs/include/logging.ja.md
> +logging セクションには、ログ設定を含みます。このセクションでは、コンテナの [FireLens](https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/using_firelens.html) ログドライバ用のログ設定パラメータを設定できます。(設定例は[こちら](../developing/sidecars.
Can we use "ログドライバ用のパラメータを設定できます" here as well?

2021-10-14 04:48 UTC, toricls commented on site/content/docs/include/logging.ja.md
> +任意項目。ログに ECS メタデータを含むかどうか。デフォルトは `true`。
This could be a very nit comment, but "含む" should be "含める" from the users' view I think?

2021-10-14 04:48 UTC, toricls commented on site/content/docs/include/network.ja.md
> +    `copilot env init` コマンドで既存の VPC をインポートして利用することや、分離されたワークロード用に VPC エンドポイントが構成された VPC を構成ができます。詳細は、[custom environment resources](../developing/custom-environment-resources.ja.md)を確認してください。
I'd put some words here to explicitly tell the nuance of "Alternatively" in the original doc

2021-10-14 04:48 UTC, toricls commented on site/content/docs/include/network.ja.md
> +Copilot は、Service が Environment 内の他の Service と通信できるようにするためのセキュリティグループを常にタスクに対して設定します。本フィールドでは、同セキュリティグループ以外に追加で紐づけたい １ つ以上のセキュリティグループ ID を指定します。
It could be a bit redundant, but I'd like to propose the below :) Happy to hear your thoughts.

```suggestion
Copilot がタスクに対して自動で設定するセキュリティグループ以外に追加で設定したいセキュリティグループがある場合にそれらの ID を指定します。複数のセキュリティグループ ID を指定可能です。(Copilot が自動設定するセキュリティグループは、同一 Environment 内の Service 間通信を可能にする目的で設定されます。)
```

2021-10-14 04:48 UTC, toricls commented on site/content/docs/include/sidecar-config.ja.md
> +サイドカーコンテナがエッセンシャルコンテナかどうか。(任意項目。デフォルトでは true)
I thought we use "必須" for "essential" in the official Japanese AWS docs, is that changed?

2021-10-14 04:48 UTC, toricls commented on site/content/docs/include/sidecar-config.ja.md
> +コンテナが unhealthy と見なされるまでに、失敗したヘルスチェックを再試行する回数です。1〜10 回を指定できます。デフォルト値は２です。
Q: Is "1〜10 回を指定できます。" intentionally added here? Because I couldn't find this sentence in the original doc.

2021-10-14 04:48 UTC, toricls commented on site/content/docs/include/storage.ja.md
> +// Simple managed EFS
Simply use "Boolean 値による指定" or something like that, to avoid the "managed EFS" wording because this could be misleading for Japanese language readers.

2021-10-14 04:48 UTC, toricls commented on site/content/docs/include/storage.ja.md
> +// Managed EFS with custom POSIX info
Same as above, just "POSIX uid/gid の指定" or something.

2021-10-14 04:48 UTC, toricls commented on site/content/docs/manifest/worker-service.ja.md
> +タスク単位の教養可能なバックログとは、`acceptable_latency` を `msg_processing_time`で割る事で計算されます。例えば、メッセージが到着後、10分以内に処理出れば良いとします。またメッセージを処理するのに平均 250 ミリ秒かかるとすると、この時、`acceptableBacklogPerTask = 10 * 60 / 0.25 = 2400` となります
Typo?

```suggestion
タスク単位の許容可能なバックログとは、`acceptable_latency` を `msg_processing_time`で割る事で計算されます。例えば、メッセージが到着後、10分以内に処理できれば良いとします。またメッセージを処理するのに平均 250 ミリ秒かかるとすると、この時、`acceptableBacklogPerTask = 10 * 60 / 0.25 = 2400` となります。各タスクは2,400 件のメッセージを処理することになります。
```

2021-10-15 02:27 UTC, isleys commented on site/content/docs/developing/publish-subscribe.ja.md
> +トピックの機能を表す名前が必要です。
Your’re right.  I think  it is a more natural expression , and will fix it.

2021-10-15 02:27 UTC, isleys commented on site/content/docs/developing/publish-subscribe.ja.md
> +Manifest の [`subscribe`](../manifest/worker-service/#subscribe) フィールドを使用して、Environment 内の他のサービスが公開する既存の SNS トピックへのサブスクリプションを定義します。この例では、前セクションの `api` サービスが公開する `orders` トピックを使用しています。また Worker Service
OK.  I'll fix it

2021-10-15 03:15 UTC, isleys commented on site/content/docs/include/sidecar-config.ja.md
> +サイドカーコンテナがエッセンシャルコンテナかどうか。(任意項目。デフォルトでは true)
Yes.  I wiil fix.

2021-10-15 04:01 UTC, isleys commented on site/content/docs/include/storage.ja.md
> +// Simple managed EFS
There are same sentence in `include/common-svc-fields.en/ja` and v1.11.0 is not change  this sentence in `common-svc-field.en/ja`.
If we change, Is it better to change both together ?

2021-10-15 04:18 UTC, isleys commented on site/content/docs/include/sidecar-config.ja.md
> +コンテナが unhealthy と見なされるまでに、失敗したヘルスチェックを再試行する回数です。1〜10 回を指定できます。デフォルト値は２です。
I intend to match current docs.
There are same sentence `include/image-healthcheck.en/ja.md(hash:9298ae)`  , and v1.11.0 is not change this sentence in `include/image-healthcheck.ja.md`.

Is "1〜10 回を指定できます。" unsecessary?

2021-10-15 04:18 UTC, isleys commented on site/content/docs/manifest/worker-service.ja.md
> +タスク単位の教養可能なバックログとは、`acceptable_latency` を `msg_processing_time`で割る事で計算されます。例えば、メッセージが到着後、10分以内に処理出れば良いとします。またメッセージを処理するのに平均 250 ミリ秒かかるとすると、この時、`acceptableBacklogPerTask = 10 * 60 / 0.25 = 2400` となります
sorry for typo. I will fix it.

2021-10-15 04:20 UTC, isleys commented on site/content/docs/include/common-svc-fields.ja.md
> +logging セクションには、ログ設定を含みます。このセクションでは、コンテナの [FireLens](https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/using_firelens.html) ログドライバ用のログ設定パラメータを設定できます。(設定例は[こちら](../developing/sidecars.
Yes, I agree with your thoughts.

2021-10-15 06:08 UTC, isleys commented on site/content/docs/include/logging.ja.md
> +任意項目。ログに ECS メタデータを含むかどうか。デフォルトは `true`。
Your idea is nice.I agree with you. it is more user friendly.
I will fix it.

2021-10-15 06:08 UTC, isleys commented on site/content/docs/include/network.ja.md
> +    `copilot env init` コマンドで既存の VPC をインポートして利用することや、分離されたワークロード用に VPC エンドポイントが構成された VPC を構成ができます。詳細は、[custom environment resources](../developing/custom-environment-resources.ja.md)を確認してください。
OK. I will try it.

2021-10-18 00:55 UTC, toricls commented on site/content/docs/include/sidecar-config.ja.md
> +コンテナが unhealthy と見なされるまでに、失敗したヘルスチェックを再試行する回数です。1〜10 回を指定できます。デフォルト値は２です。
Interesting, but I think we should remove that sentence here because at least the English version doesn't have a corresponding one.

2021-10-18 00:55 UTC, toricls commented on site/content/docs/include/storage.ja.md
> +// Simple managed EFS
+1 for changing both 🙌

2021-10-18 00:57 UTC, toricls commented on site/content/docs/include/sidecar-config.ja.md
> +コンテナが unhealthy と見なされるまでに、失敗したヘルスチェックを再試行する回数です。1〜10 回を指定できます。デフォルト値は２です。
I mean, removing it from `include/image-healthcheck.ja.md` as well

2021-10-25 19:06 UTC, isleys commented
Sorry for the late response. I fix to reflect the review comments.

2021-10-26 23:58 UTC, toricls approved these changes

2021-10-26 23:58 UTC, toricls commented
Great work @isleys, thanks!

2021-10-27 00:31 UTC, efekarakus approved these changes

2021-10-27 00:32 UTC, merged