docs(ja): periodic update for v1.25
aws/copilot-cli pull request #4439
Opened 2023-01-30 22:21 UTC by shingos

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

2023-01-31 12:59 UTC, hkford requested changes
Thank you for opening this PR and fixing some broken links. Left some comments.

2023-01-31 12:59 UTC, hkford commented on site/content/blogs/release-v125.ja.md
> +現在、Addon は CloudFormation を使ったモデリングのみ対応しています。Environment Addon の場合は以下が必須です。
I think モデリング here is too vague. How about "CloudFormation を使ったリソースの定義のみをサポートしています" or something?

2023-01-31 12:59 UTC, hkford commented on site/content/blogs/release-v125.ja.md
> +上記の例の続きで、`db-front` Service が `MyTable` にアクセスするようにしたいとします。`db-front` Service にアクセスするための IAM ポリシーを持つワークロード Addmon を作成します。
typo: Addmon to Addon

2023-01-31 12:59 UTC, hkford commented on site/content/blogs/release-v125.ja.md
> +<a id="import-values-from-cloudformation-stacks-in-workload-manifests"></a>
What is this html element?

2023-01-31 12:59 UTC, hkford commented on site/content/blogs/release-v125.ja.md
> +<a id="static-content-delivery-with-cloudfront"></a>
What is this html element?

2023-01-31 12:59 UTC, hkford commented on site/content/blogs/release-v125.ja.md
> +- [GitHub](https://github.com/aws/copilot-cli/releases/tag/v1.24.0) でリリースノートの全文を読む
I think the link to GitHub release note should be v1.25.0

2023-01-31 12:59 UTC, hkford commented on site/content/docs/concepts/environments.ja.md
> +既存の Environment リソースをインポートする、コマンドでフラグを使う、[env Manifest](../manifest/environment.ja.md) を変更するといった方法で、デフォルトの設定をすることができます。もし、現在設定可能なリソースよりも多くの種類のリソースをカスタマイズしたい場合は、お気軽にユースケースを添えた GitHub イシューを作成してください！
typo: Manifest to manifest because `env manifest` here is one of Copilot commands.

2023-01-31 12:59 UTC, hkford commented on site/content/docs/developing/addons/environment.ja.md
> +ワークロードの追加リソース ([Load Balanced Web Service](../../manifest/lb-web-service.ja.md) や [Scheduled Job](../../manifest/scheduled-job.ja.md) など) を定義することができます。
LB web service and scheduled job is examples of workloads, so how about "ワークロード([Load Balanced Web Service]()...)の追加のリソースを定義することができます"?

2023-01-31 12:59 UTC, hkford commented on site/content/docs/developing/addons/environment.ja.md
> +## どのように S3 バケット、DDB テーブル、Aurora サーバーレスクラスターを追加するのか？
I think "Aurora Serverless クラスター" is better because l4 does so.

2023-01-31 12:59 UTC, hkford commented on site/content/docs/developing/addons/workload.ja.md
> +## どのように S3 バケット、DDB テーブル、Aurora サーバーレスクラスターを追加するのか？
I think "Aurora Serverless クラスター" is better because l4 does so.

2023-01-31 12:59 UTC, hkford commented on site/content/docs/developing/addons/workload.ja.md
> +* ECS タスクロールや App Runner インスタンスロールに追加のポリシーを追加する必要がある場合、追加のパーミッションを保持する [IAM ManagedPolicy](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html) アド
アドオンリソース to Addon リソース

2023-01-31 12:59 UTC, hkford commented on site/content/docs/developing/addons/workload.ja.md
> +* もし、任意のリソースの値を環境変数として注入したい場合は、ECS タスクに[出力](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html)を作成することができます。これはコンテナにインジェクトされ、大文字の SNAKE_CASE で環境変数としてア
できる to できるようになります

2023-01-31 12:59 UTC, hkford commented on site/content/docs/developing/addons/workload.ja.md
> +ワークロードレベルの DynamoDB テーブルアドオンのテンプレート例です。
How about "ワークロードレベルで DynamoDB テーブルを作成する Addon のテンプレート例です" or something?

2023-02-01 08:42 UTC, shingos commented on site/content/blogs/release-v125.ja.md
> +現在、Addon は CloudFormation を使ったモデリングのみ対応しています。Environment Addon の場合は以下が必須です。
Thank you.

2023-02-01 08:42 UTC, shingos commented on site/content/blogs/release-v125.ja.md
> +上記の例の続きで、`db-front` Service が `MyTable` にアクセスするようにしたいとします。`db-front` Service にアクセスするための IAM ポリシーを持つワークロード Addmon を作成します。
Oops, thanks.

2023-02-01 08:43 UTC, shingos commented on site/content/blogs/release-v125.ja.md
> +<a id="import-values-from-cloudformation-stacks-in-workload-manifests"></a>
For links in documents. There is an anchor at the top that links to this location.

2023-02-01 08:51 UTC, shingos commented on site/content/docs/concepts/environments.ja.md
> +既存の Environment リソースをインポートする、コマンドでフラグを使う、[env Manifest](../manifest/environment.ja.md) を変更するといった方法で、デフォルトの設定をすることができます。もし、現在設定可能なリソースよりも多くの種類のリソースをカスタマイズしたい場合は、お気軽にユースケースを添えた GitHub イシューを作成してください！
This is a typo, but in context, isn't it "Environment Manifest" rather than command? This link jumps to the description of the env manifest.

2023-02-01 09:24 UTC, hkford commented on site/content/blogs/release-v125.ja.md
> +<a id="import-values-from-cloudformation-stacks-in-workload-manifests"></a>
Is this necessary for Japanese documentation? [English documentation](https://github.com/aws/copilot-cli/blob/mainline/site/content/blogs/release-v125.en.md?plain=1#L286) does not seem to have it.

2023-02-01 09:46 UTC, hkford approved these changes
Thank you @shingos for huge contribution!

2023-02-01 18:48 UTC, Lou1415926 approved these changes
Thank you very much for contributing to the docs!!! ❤️

2023-02-01 19:01 UTC, merged