docs(ja): periodic update
aws/copilot-cli pull request #4588
Opened 2023-03-06 04:24 UTC by riita10069

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

2023-03-06 15:10 UTC, hkford requested changes
Thank you for draft translation. Left some comments.

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +title: 'AWS Copilot v1.26: CloudWatch アラーム、環境アドオン用の「ストレージ初期化」、および RDWS シークレットサポートによるロールバックの自動化'
Could you use Copilot terms here?
環境アドオン -> Environment Addon cf) https://aws.github.io/copilot-cli/ja/docs/developing/addons/environment/

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +# AWS Copilot v1.26: CloudWatchアラームによるロールバックの自動化、envアドオン用 `storage init`、RDWSシークレットのサポート。
Please be consistent with title field in l5.

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +
Could you add an anchor here?
`<a id="service-alarm-based-rollback"></a>`

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +[カスタム CloudWatch アラーム](https://docs.aws.amazon.com/AmazonECS/latest/userguide/deployment-alarm-failure.html) で [ECS のデプロイ状況を監視する](https://aws.amazon.com/blogs/containers/automate-rollbacks-for-amazon
Could you reference Japanese documents?
custom CloudWatch alarm -> https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/userguide/deployment-alarm-failure.html
circuit breaker -> https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/deployment-circuit-breaker.html

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +バックエンド、ワーカー、または負荷分散されたウェブサービスのマニフェストで、独自の既存の CloudWatch アラームをインポートできます。
Please use Copilot terms here. Backend, Worker and Load Balanced Web Service Manifest
cf) https://aws.github.io/copilot-cli/ja/docs/concepts/services/#service_1

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +また、Copilotにお好みの閾値を設定して、CPUやメモリ使用率アラームを作成してもらうこともできます。
Could you add space between 't' and 'に', 'U' and 'や'?

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +ワーカーサービスの場合は、`ApproximateNumberOfMessagesDelayed` を監視するアラームを作成することもできます。
ワーカーサービス to Worker Service

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +Copilotがお客様に代わってアラームを作成する際、いくつかのデフォルトが設定されます。
Could you add space between 't' and 'が' ?

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +サービスマニフェストでロールバックアラームを設定すると、最初のデプロイ後に (ロールバックする既存のデプロイがないときに) `svc deploy` を実行するたびに、ECS はアラームをポーリングし、違反があった場合はロールバックをトリガーします。
サービスマニフェスト to Service Manifest

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +## 環境アドオン用 `storage init`
環境アドオン to Environment Addon

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +以前は、`copilot storage init` はワークロードに接続されたストレージアドオンだけをサポートしていました。
Please use Copilot terms in l72 and l73.
アドオン -> Addon, サービス -> Service

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +そして、`copilot env delete` を実行して環境を削除するまで削除されません。
環境 to Environment

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +これで、環境ストレージアドオンを作成できるようになりました。ストレージは `copilot env deploy` を実行するとデプロイされます。
I think this sentence implies Copilot previously support only storage addons attached to workloads and now it support Environment Storage Addon. So how about 'このバージョンから Copilot は Environment に紐づいたストレージ Addon を作成できるようになりました' or something.

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +ワークロードストレージと同様に、環境ストレージも内部的には [環境アドオン](../docs/developing/addons/environment.ja.md) のもう1つです。
環境 to Environment and アドオン to Addon
Also 'もう１つです' seems vague to me. How about '内部的には Environment Addon と同じです' or something?

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +### [サービスごとのデータベース](https://docs.aws.amazon.com/prescriptive-guidance/latest/modernization-data-persistence/database-per-service.html) のデフォルト
Please reference [the Japanese documentation](https://docs.aws.amazon.com/ja_jp/prescriptive-guidance/latest/modernization-data-persistence/database-per-service.html).
Also this title seems to suggest Copilot generates manifests based on Database-per-service pattern by default, so how about 'デフォルトでサービスごとのデータベースパターンを採用' or something?

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +複数のサービスで共有されるモノリスストレージの代わりに。
Could you stop inversion here and translate the original sentences like 'マイクロサービスの世界では、複数サービスで共有されるモノリスなストレージの代わりに、データストレージをそれぞれマイクロサービス専用に~' or something?

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +Copilotでは、このサービスごとのデータベースパターンに従うことを推奨しています。デフォルトでは、Copilotが生成するストレージリソース
Please add a space between 't' and 'で', 'が'.

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +は、1 つのサービスまたはジョブによってアクセスされることを前提としています。
サービス to Service, ジョブ to Job

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +このパターンでは、マイクロサービスの核となる特徴であるルーズカップリングが維持されます。
I think '疎結合' instead of 'ルーズカップリング ' is more easy to understand for readers.

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +ただし、各ユーザーには独自の状況があります。データストレージを複数のサービス間で共有する必要がある場合は、
サービス to Service

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +コパイロットで生成された CloudFormation テンプレートを変更して、目的を達成することができます。
コパイロット to Copilot

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +これは、`copilot/environments` ディレクトリの下に生成されます。さらに、必要なアクセスポリシーを生成します。これは api サービスを許可するポリシーです
How about 'これは "movies" ストレージへのアクセスを "api" Service に許可するポリシーです。アクセスポリシーはワークロード addon として作成されるので、"api" Service と同じタイミングでデプロイされ削除されます'

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +ストレージのタイプ、およびストレージに接するワークロードのタイプによって、Copilotが生成するCloudFormationファイルの内容は異なる場合があります。
Please add a space between English words and Japanese words like 't' and 'が', 'る' and 'C', 'n' and 'フ'.

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +
Could you add an anchor here?
`<a id="storage-init-for-environment-addons"></a>`

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +
Could you add an anchor here?
<a id="request-driven-web-service-secrets-support"></a>

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +## リクエスト主導型Webサービスシークレットのサポート
リクエスト主導型Webサービス to Request-Driven Web Service

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +負荷分散型Webサービスなどの他のサービスタイプと同様に、最初にシークレットに次のタグを追加する必要があります。
負荷分散型Webサービス to Load Balanced Web Service

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +次に、リクエスト主導型Webサービスのマニフェストを次のように更新するだけです。
リクエスト主導型Webサービス to Request-Driven Web Service
マニフェスト to Manifest

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +これでデプロイをすると、サービスはシークレットに環境変数としてアクセスできるようになりました。
サービス to Service

2023-03-06 15:10 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +[マニフェスト仕様](../docs/manifest/rd-web-service/#secrets) を参照してください。サービスにシークレットを挿入する方法の詳細については、[シークレットページ](../docs/developing/secrets.ja.md) を参照してください。
マニフェスト to Manifest
サービス to Service
シークレットページ to シークレット cf) https://aws.github.io/copilot-cli/ja/docs/developing/secrets/

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +`copilot storage init` は、アドオンとして新しいストレージリソースを作成します。
アドオン to Addon

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +デフォルトでは、Copilotは「Database per Service」パターンに従っています。
Please add a space between 't' and 'は'.

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +ストレージは、サービスのコンテナ内から、ストレージリソースの名前またはリソースにアクセスするためのクレデンシャル情報を保持する環境変数を介してアクセスできます。
サービス to Service

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +    の場合、Copilotが生成したCloudFormationテンプレートを変更することで、目的を達成することができます。
How about '各ユーザーには独自の状況があります。データストレージを複数の Service 間で共有する必要がある場合は、Copilot で生成された CloudFormation テンプレートを変更して、目的を達成することができます。'

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +ストレージリソースは、[ワークロードアドオン](../developing/addons/workload.ja.md)として作成することができます。
アドオン to Addon

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +これは、サービスやジョブの1つにアタッチされ、ワークロードと同時にデプロイされ削除されます。
サービス to Service, ジョブ to Job
I think '関連づけられ' instead of 'アタッチされ' is more easy to understand.

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +例えば、`copilot svc deploy --name api`を実行すると、リソースは「api」とともにターゲット環境にデプロイされます。
ターゲット環境 to ターゲット Environment

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +また、ストレージリソースは [環境アドオン](../developing/addons/environment.ja.md) として作成することができます。
環境 to Environment

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +これは環境にアタッチされ、同時にデプロイされ削除されます。
How about 'Environment に関連づけられ、Environment と同時にデプロイされ削除されます'?

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +例えば、`copilot env deploy --name test`を実行すると、test という環境と一緒にリソースがデプロイされます。
環境 to Environment

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +このコマンドを実行すると、CLI は `copilot/service` ディレクトリ内に、`addons` サブディレクトリが存在しなければ作成します。`copilot svc deploy` を実行すると、新規に初期化されたストレージリソースが、デプロイ先の環境に作成されます。デフォルトでは、`storage init` で指定した Service のみが、そのストレージリソースにアクセスで
環境 to Environment

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +`copilot storage init`は、アドオンとして新しいストレージリソースを作成します。"api "サービスがフロントする "my-bucket"という名前の S3 バケット環境を作成します。
アドオン to Addon
サービス to Service
S3 バケット環境 to S3 バケットを Environment 単位で作成します

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +Copilotは、S3バケット、DDBテーブル、またはAurora Serverlessクラスタを指定するCloudformationテンプレートを`addons`ディレクトリに書き込む。
How about 'Copilot は S3 バケット、DynamoDB テーブル、または Aurora Serverless クラスターを指定する CloudFormation テンプレートを `addons` ディレクトリに書き出します'?

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +`copilot [svc/job/env] deploy`を実行すると、CLIはこのテンプレートを addons ディレクトリの他のすべてのテンプレートとマージして、Service または環境に関連するネストされたスタックを作成します。
Please add a space between 'I' and 'は'.
addons to `addons`
環境 to Environment

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +このネストされたスタックには、サービスまたは環境に関連付けられたすべての [追加リソース](../developing/addons/workload.ja.md) が記述され、Service または環境がデプロイされる場所に展開されます。
サービス to Service
環境 to Environment
追加リソース to Addon リソース
環境 to Environment

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +#### Service に接続されたS3ストレージ
How about 'Serivce に関連づけられた S3 ストレージ'?

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +Service に接続するS3バケット用のCloudFormationテンプレートが生成されます。
How about 'Service に関連づけられた S3 バケット用の CloudFormation テンプレート'?

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +このコマンドを実行すると、test 環境と prod 環境の2つのバケットが展開され、それぞれの環境の fe Service からのみアクセスできるようになります。
環境 to Environment

2023-03-06 15:10 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +#### 環境に接続されたS3ストレージ
How about 'Environment に関連づけられた S3 ストレージ'?

2023-03-06 15:10 UTC, hkford commented on site/content/docs/credentials.ja.md
> +AWS Copilotは、AWS APIへのアクセス、[アプリケーションのメタデータ](concepts/applications.ja.md)の保存と検索、アプリケーションのワークロードの展開と運用にAWSクレデンシャルを使用します。
Please add a space between 't' and 'は', 'に' and 'A', 'S' and 'ク'.

2023-03-06 15:10 UTC, hkford commented on site/content/docs/developing/addons/environment.ja.md
> +Copilotには、特定の種類のアドオンを作成するのに役立つ以下のコマンドが用意されています。
Please add a space between 't' and 'に'.
アドオン to Addon

2023-03-06 15:10 UTC, hkford commented on site/content/docs/developing/addons/environment.ja.md
> +* [`storage init`](../../commands/storage-init.ja.md) は、DynamoDBテーブル、S3バケット、またはAurora Serverlessクラスターを作成します。
DynamoDBテーブル、S3バケット、またはAurora Serverlessクラスター to DynamoDB テーブル、S3 バケット、または Aurora Serverless クラスター

2023-03-06 15:10 UTC, hkford commented on site/content/docs/developing/domain.ja.md
> +生成されるACM証明書をより細かく制御したい場合や、[default `alias` options](#customized-domain-alias) が十分に柔軟でない場合は、環境を作る際に `--import-cert-arns` フラッグを指定して、別名を含む検証済みのACM証明書をインポートすることが可能です。例えば、以下のような感じです。
Please add spaces between 'ACM 証明書' and its surroundings.
環境 to Environment
フラッグ to フラグ

2023-03-06 15:10 UTC, hkford commented on site/content/docs/developing/domain.ja.md
> +また、[環境マニフェスト](../manifest/environment.en.md)を修正することで、後からいつでも証明書を追加することができます。
環境マニフェスト to Environment Manifest

2023-03-06 15:10 UTC, hkford commented on site/content/docs/developing/storage.ja.md
> +### 環境ストレージ
環境 to Environment

2023-03-06 15:10 UTC, hkford commented on site/content/docs/developing/storage.ja.md
> +`-l` フラグは `--lifecycle` の略である。上記の例では、`-l` フラグの値は `workload` です。
である to です

2023-03-06 15:10 UTC, hkford commented on site/content/docs/developing/storage.ja.md
> +これは、ストレージリソースがサービスアドオンまたはジョブアドオンとして作成されることを意味します。
サービスアドオン to Service Addon
ジョブアドオン to Job Addon

2023-03-06 15:10 UTC, hkford commented on site/content/docs/developing/storage.ja.md
> +また、サービスやジョブを削除してもストレージを維持したい場合は、環境ストレージリソースを作成することができます。環境ストレージリソースは環境アドオンとして作成され、`copilot env deploy`を実行すると展開され、`copilot env delete`を実行するまで削除されることはありません。
サービスやジョブ to Service や Job
環境 to Environment
環境アドオン to Environment Addon

2023-03-06 15:10 UTC, hkford commented on site/content/docs/include/deployment.ja.md
> +    デプロイの開始時にアラームが「アラーム中」状態にある場合、Amazon ECS はそのデプロイの間、アラームを監視しません。詳細については、[こちらのドキュメント](https://docs.aws.amazon.com/AmazonECS/latest/userguide/deployment-alarm-failure.html)をお読みください。
Please reference the Japanese documentation.

2023-03-06 15:10 UTC, hkford commented on site/content/docs/include/deployment.ja.md
> +文字列のリストとして、[デプロイのロールバック](https://docs.aws.amazon.com/AmazonECS/latest/userguide/deployment-alarm-failure.html)を引き起こす可能性のある、サービスに関連付ける既存のCloudWatchアラームの名前を指定します。
Please reference the Japanese documentation.
サービス to Service
Please add spaces between 'の' and 'C', 'h' and 'ア'.

2023-03-06 15:10 UTC, hkford commented on site/content/docs/include/deployment.ja.md
> +    デプロイの開始時にアラームが「アラーム中」状態にある場合、Amazon ECS はそのデプロイの間、アラームを監視しません。詳細については、[こちらのドキュメント](https://docs.aws.amazon.com/AmazonECS/latest/userguide/deployment-alarm-failure.html)をお読みください。
アラーム中 to In alarm

2023-03-06 15:10 UTC, hkford requested changes
Thank you for draft translation. Left some comments.

2023-03-15 14:38 UTC, hkford requested changes
Thank you for updating PR. Left comments.

2023-03-15 14:38 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +Copilot では、この Service ごとのデータベースパターンに従うことを推奨しています。デフォルトでは、Copilot が生成するストレージリソースは、1 つのサービスまたは Job によってアクセスされることを前提としています。
サービス to Service

2023-03-15 14:38 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +複数のサービスで共有されるモノリスストレージの代わりに。
Could you stop inversion here and translate the original sentences like 'マイクロサービスの世界では、複数サービスで共有されるモノリスなストレージの代わりに、データストレージをそれぞれマイクロサービス専用に~' or something?

2023-03-15 14:38 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +Copilot を使用して、シークレット (SSM パラメータストアまたは AWS シークレットマネージャーから) を環境変数として App Runner サービスに追加できるようになりました。
SSM パラメータストア to Systems Manager パラメータストア，シークレットマネージャー to Secrets Manager
cf) https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/developerguide/specifying-sensitive-data-parameters.html
cf) https://aws.amazon.com/jp/secrets-manager/

2023-03-15 14:38 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +Load Balanced Web Service などの他のサービスタイプと同様に、最初にシークレットに次のタグを追加する必要があります。
サービス to Service

2023-03-15 14:38 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +詳細については、[ストレージページ](../docs/developing/storage.ja.md) もチェックしてください。
ストレージページ to ストレージ
cf) https://aws.github.io/copilot-cli/ja/docs/developing/storage/

2023-03-15 14:38 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +デフォルトでは、Copilot は「Database per Service」パターンに従っています。
I think this should be consistent with the title of [this page](https://docs.aws.amazon.com/ja_jp/prescriptive-guidance/latest/modernization-data-persistence/database-per-service.html): Database-per-service パターン

2023-03-15 14:38 UTC, hkford commented on site/content/blogs/release-v126.ja.md
> +### デフォルトで[サービスごとのデータベースパターン](https://docs.aws.amazon.com/ja_jp/prescriptive-guidance/latest/modernization-data-persistence/database-per-service.html) を採用
I think this should be consistent with the title of [this page](https://docs.aws.amazon.com/ja_jp/prescriptive-guidance/latest/modernization-data-persistence/database-per-service.html): Database-per-service パターン

2023-03-15 14:38 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +このネストされたスタックには、サービスまたは Environment に関連付けられたすべての [Addon リソース](../developing/addons/workload.ja.md) が記述され、Service または Environment がデプロイされる場所に展開されます。
サービス to Service

2023-03-15 14:38 UTC, hkford commented on site/content/docs/commands/storage-init.ja.md
> +#### Service に関連づけられたS3ストレージ
Please add a space between 'た' and 'S', '3' and 'ス'.

2023-03-15 14:38 UTC, hkford commented on site/content/docs/developing/addons/environment.ja.md
> +Copilot には、特定の種類のアドオンを作成するのに役立つ以下のコマンドが用意されています。
アドオン to Addon

2023-03-15 14:38 UTC, hkford commented on site/content/docs/developing/domain.ja.md
>  Copilot が Service に割り当てるデフォルトのドメイン名を使いたくない場合は、[Manifest](../manifest/overview.ja.md) の `alias` セクションを編集して、サービスのカスタム[エイリアス](https://docs.aws.amazon.com/ja_jp/Route53/latest/DeveloperGuide/resource-rec
サービス to Service

2023-03-15 14:38 UTC, hkford commented on site/content/docs/include/deployment.ja.md
> +文字列のリストとして、[デプロイのロールバック](https://docs.aws.amazon.com/ja_jp/AmazonECS/latest/userguide/deployment-alarm-failure.html)を引き起こす可能性のある、サービスに関連付ける既存のCloudWatchアラームの名前を指定します。
サービス to Service
Please add spaces between 'の' and 'C', 'h' and 'ア'.

2023-03-20 04:54 UTC, hkford approved these changes
Thank you @riita10069 for your contribution! Approved your PR.

2023-03-20 08:25 UTC, riita10069 commented
There were a lot of corrections and I made you go through a lot of trouble. Sorry about that. And thanks for the feedback.

2023-03-20 15:23 UTC, efekarakus approved these changes
Thank you both so much!

2023-03-20 15:41 UTC, merged