docs: update tag flag description
aws/copilot-cli pull request #5004
Opened 2023-06-16 23:06 UTC by iamhopaul123

Resolves https://github.com/aws/copilot-cli/issues/4973

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

2023-06-19 16:15 UTC, huanjani commented on internal/pkg/cli/flag.go
> +	imageTagFlagDescription     = `Optional. The container image tag for image Copilot builds from the Dockerfile.`
```suggestion
	imageTagFlagDescription     = `Optional. The tag for the container image Copilot builds from the Dockerfile.`
```

2023-06-19 16:15 UTC, huanjani commented on site/content/docs/commands/deploy.en.md
> +      --tag string                     Optional. The container image tag for image Copilot builds from the Dockerfile.
```suggestion
      --tag string                     Optional. The for the container image Copilot builds from the Dockerfile.
```

2023-06-19 16:16 UTC, huanjani commented on site/content/docs/commands/deploy.ja.md
> +      --tag string                     Optional. The container image tag for image Copilot builds from the Dockerfile.
```suggestion
      --tag string                     Optional. The tag for the container image Copilot builds from the Dockerfile..
```

2023-06-19 16:17 UTC, huanjani commented on site/content/docs/commands/init.en.md
> +      --tag string          Optional. The container image tag for image Copilot builds from the Dockerfile.
```suggestion
      --tag string          Optional. The tag for the container image Copilot builds from the Dockerfile..
```

2023-06-19 16:17 UTC, huanjani commented on site/content/docs/commands/init.ja.md
> +      --tag string          Optional. The container image tag for image Copilot builds from the Dockerfile.
```suggestion
      --tag string          Optional. The tag for the container image Copilot builds from the Dockerfile.
```

2023-06-19 16:17 UTC, huanjani commented on site/content/docs/commands/job-deploy.en.md
> +      --tag string                     Optional. The container image tag for image Copilot builds from the Dockerfile.
```suggestion
      --tag string                     Optional. The tag for the container image Copilot builds from the Dockerfile.
```

2023-06-19 16:18 UTC, huanjani commented on site/content/docs/commands/job-deploy.ja.md
> +      --tag string                     Optional. The container image tag for image Copilot builds from the Dockerfile.
```suggestion
      --tag string                     Optional. The tag for the container image Copilot builds from the Dockerfile.
```

2023-06-19 16:18 UTC, huanjani commented on site/content/docs/commands/job-package.en.md
> +      --tag string          Optional. The container image tag for image Copilot builds from the Dockerfile.
```suggestion
      --tag string          Optional. The tag for the container image Copilot builds from the Dockerfile.
```

2023-06-19 16:18 UTC, huanjani commented on site/content/docs/commands/job-package.ja.md
> +      --tag string          Optional. The container image tag for image Copilot builds from the Dockerfile.
```suggestion
      --tag string          Optional. The tag for the container image Copilot builds from the Dockerfile.
```

2023-06-19 16:18 UTC, huanjani commented on site/content/docs/commands/svc-deploy.en.md
> +      --tag string                     Optional. The container image tag for image Copilot builds from the Dockerfile.
```suggestion
      --tag string                     Optional. The tag for the container image Copilot builds from the Dockerfile.
```

2023-06-19 16:18 UTC, huanjani commented on site/content/docs/commands/svc-deploy.ja.md
> +      --tag string                     Optional. The container image tag for image Copilot builds from the Dockerfile.
```suggestion
      --tag string                     Optional. The tag for the container image Copilot builds from the Dockerfile.
```

2023-06-19 16:19 UTC, huanjani reviewed
Thanks for fixing this!

2023-06-19 16:19 UTC, huanjani commented
Related: #4983

2023-06-19 17:00 UTC, Lou1415926 approved these changes

2023-06-19 17:00 UTC, Lou1415926 commented on site/content/docs/commands/deploy.en.md
> +3. [Optional] Push the image to ECR
Are we putting `[Optional]` here because people could specify `image.location` too? If so, do you think we can write it like this:
```
1. When seeing`image.build`, build your local Dockerfile into an image
     a. Tag it with the value from `--tag` or the latest git sha (if you're in a git directory)
     b. Push the image to ECR
2. Package...
```

The main nit is that it sort of sounds like you can have 1, but optionally have 2 and 3; while in reality 2 and 3 are bound to happen if you have 1. Also it is not clear to the users how to trigger the build and how not to 💭

2023-06-20 19:59 UTC, dannyrandall requested changes

2023-06-20 19:59 UTC, dannyrandall commented on internal/pkg/cli/flag.go
> +	imageTagFlagDescription     = `Optional. The tag for the container image Copilot builds from the Dockerfile.`
```suggestion
	imageTagFlagDescription     = `Optional. The tag for the container images Copilot builds from Dockerfiles.`
```

2023-06-20 20:10 UTC, dannyrandall approved these changes

2023-06-20 20:27 UTC, merged